# Generated by Django 3.2.6 on 2022-01-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('WORKING', 'WORKING'), ('DUE', 'DUE'), ('COMPLETED', 'COMPLETED')], max_length=10),
        ),
    ]
