# Generated by Django 3.2.6 on 2022-01-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20220124_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('WORKING', 'WORKING'), ('DUE', 'DUE'), ('COMPLETED', 'COMPLETED')], default='1', max_length=10),
        ),
    ]
