# Generated by Django 3.2.6 on 2022-01-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('WORKING', 'WORKING'), ('DUE', 'DUE'), ('COMPLETED', 'COMPLETED')], default='OPEN', max_length=10),
        ),
    ]
